// Generated by beansc bindgen for arm64-apple-darwin.

package sys

pub extern "C" struct Pcre2CalloutBlock16 {
    pub version: u32
    pub callout_number: u32
    pub capture_top: u32
    pub capture_last: u32
    pub offset_vector: RawPtr<u64>
    pub mark: RawPtr<u16>
    pub subject: RawPtr<u16>
    pub subject_length: u64
    pub start_match: u64
    pub current_position: u64
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u16>
    pub callout_flags: u32
}

pub extern "C" struct Pcre2CalloutBlock32 {
    pub version: u32
    pub callout_number: u32
    pub capture_top: u32
    pub capture_last: u32
    pub offset_vector: RawPtr<u64>
    pub mark: RawPtr<u32>
    pub subject: RawPtr<u32>
    pub subject_length: u64
    pub start_match: u64
    pub current_position: u64
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u32>
    pub callout_flags: u32
}

pub extern "C" struct Pcre2CalloutBlock8 {
    pub version: u32
    pub callout_number: u32
    pub capture_top: u32
    pub capture_last: u32
    pub offset_vector: RawPtr<u64>
    pub mark: RawPtr<u8>
    pub subject: RawPtr<u8>
    pub subject_length: u64
    pub start_match: u64
    pub current_position: u64
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u8>
    pub callout_flags: u32
}

pub extern "C" struct Pcre2CalloutEnumerateBlock16 {
    pub version: u32
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_number: u32
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u16>
}

pub extern "C" struct Pcre2CalloutEnumerateBlock32 {
    pub version: u32
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_number: u32
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u32>
}

pub extern "C" struct Pcre2CalloutEnumerateBlock8 {
    pub version: u32
    pub pattern_position: u64
    pub next_item_length: u64
    pub callout_number: u32
    pub callout_string_offset: u64
    pub callout_string_length: u64
    pub callout_string: RawPtr<u8>
}

pub extern "C" opaque struct Pcre2Code16

pub extern "C" opaque struct Pcre2Code32

pub extern "C" opaque struct Pcre2Code8

pub extern "C" opaque struct Pcre2CompileContext16

pub extern "C" opaque struct Pcre2CompileContext32

pub extern "C" opaque struct Pcre2CompileContext8

pub extern "C" opaque struct Pcre2ConvertContext16

pub extern "C" opaque struct Pcre2ConvertContext32

pub extern "C" opaque struct Pcre2ConvertContext8

pub extern "C" opaque struct Pcre2GeneralContext16

pub extern "C" opaque struct Pcre2GeneralContext32

pub extern "C" opaque struct Pcre2GeneralContext8

pub extern "C" opaque struct Pcre2JitStack16

pub extern "C" opaque struct Pcre2JitStack32

pub extern "C" opaque struct Pcre2JitStack8

pub extern "C" opaque struct Pcre2MatchContext16

pub extern "C" opaque struct Pcre2MatchContext32

pub extern "C" opaque struct Pcre2MatchContext8

pub extern "C" opaque struct Pcre2MatchData16

pub extern "C" opaque struct Pcre2MatchData32

pub extern "C" opaque struct Pcre2MatchData8

pub extern "C" struct Pcre2SubstituteCalloutBlock16 {
    pub version: u32
    pub input: RawPtr<u16>
    pub output: RawPtr<u16>
    pub output_offsets: [u64; 2]
    pub ovector: RawPtr<u64>
    pub oveccount: u32
    pub subscount: u32
}

pub extern "C" struct Pcre2SubstituteCalloutBlock32 {
    pub version: u32
    pub input: RawPtr<u32>
    pub output: RawPtr<u32>
    pub output_offsets: [u64; 2]
    pub ovector: RawPtr<u64>
    pub oveccount: u32
    pub subscount: u32
}

pub extern "C" struct Pcre2SubstituteCalloutBlock8 {
    pub version: u32
    pub input: RawPtr<u8>
    pub output: RawPtr<u8>
    pub output_offsets: [u64; 2]
    pub ovector: RawPtr<u64>
    pub oveccount: u32
    pub subscount: u32
}

pub extern "C" fn pcre2_config_8(arg0: u32, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_general_context_copy_8(arg0: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2GeneralContext8>
pub extern "C" fn pcre2_general_context_create_8(arg0: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg1: fn(RawPtr<u8>, RawPtr<u8>), arg2: RawPtr<u8>) -> RawPtr<Pcre2GeneralContext8>
pub extern "C" fn pcre2_general_context_free_8(arg0: RawPtr<Pcre2GeneralContext8>)
pub extern "C" fn pcre2_compile_context_copy_8(arg0: RawPtr<Pcre2CompileContext8>) -> RawPtr<Pcre2CompileContext8>
pub extern "C" fn pcre2_compile_context_create_8(arg0: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2CompileContext8>
pub extern "C" fn pcre2_compile_context_free_8(arg0: RawPtr<Pcre2CompileContext8>)
pub extern "C" fn pcre2_set_bsr_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_character_tables_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_compile_extra_options_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_max_pattern_length_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_pattern_compiled_length_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_varlookbehind_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_newline_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_parens_nest_limit_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_compile_recursion_guard_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: fn(u32, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_optimize_8(arg0: RawPtr<Pcre2CompileContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_convert_context_copy_8(arg0: RawPtr<Pcre2ConvertContext8>) -> RawPtr<Pcre2ConvertContext8>
pub extern "C" fn pcre2_convert_context_create_8(arg0: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2ConvertContext8>
pub extern "C" fn pcre2_convert_context_free_8(arg0: RawPtr<Pcre2ConvertContext8>)
pub extern "C" fn pcre2_set_glob_escape_8(arg0: RawPtr<Pcre2ConvertContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_glob_separator_8(arg0: RawPtr<Pcre2ConvertContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_pattern_convert_8(arg0: RawPtr<u8>, arg1: u64, arg2: u32, arg3: RawPtr<RawPtr<u8> >, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2ConvertContext8>) -> i32
pub extern "C" fn pcre2_converted_pattern_free_8(arg0: RawPtr<u8>)
pub extern "C" fn pcre2_match_context_copy_8(arg0: RawPtr<Pcre2MatchContext8>) -> RawPtr<Pcre2MatchContext8>
pub extern "C" fn pcre2_match_context_create_8(arg0: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2MatchContext8>
pub extern "C" fn pcre2_match_context_free_8(arg0: RawPtr<Pcre2MatchContext8>)
pub extern "C" fn pcre2_set_callout_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: fn(RawPtr<Pcre2CalloutBlock8>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_callout_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: fn(RawPtr<Pcre2SubstituteCalloutBlock8>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_case_callout_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: fn(RawPtr<u8>, u64, RawPtr<u8>, u64, i32, RawPtr<u8>) -> u64, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_depth_limit_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_heap_limit_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_match_limit_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_offset_limit_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_recursion_limit_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_recursion_memory_management_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg2: fn(RawPtr<u8>, RawPtr<u8>), arg3: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_compile_8(arg0: RawPtr<u8>, arg1: u64, arg2: u32, arg3: RawPtr<i32>, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2CompileContext8>) -> RawPtr<Pcre2Code8>
pub extern "C" fn pcre2_code_free_8(arg0: RawPtr<Pcre2Code8>)
pub extern "C" fn pcre2_code_copy_8(arg0: RawPtr<Pcre2Code8>) -> RawPtr<Pcre2Code8>
pub extern "C" fn pcre2_code_copy_with_tables_8(arg0: RawPtr<Pcre2Code8>) -> RawPtr<Pcre2Code8>
pub extern "C" fn pcre2_pattern_info_8(arg0: RawPtr<Pcre2Code8>, arg1: u32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_callout_enumerate_8(arg0: RawPtr<Pcre2Code8>, arg1: fn(RawPtr<Pcre2CalloutEnumerateBlock8>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_match_data_create_8(arg0: u32, arg1: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2MatchData8>
pub extern "C" fn pcre2_match_data_create_from_pattern_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2MatchData8>
pub extern "C" fn pcre2_match_data_free_8(arg0: RawPtr<Pcre2MatchData8>)
pub extern "C" fn pcre2_dfa_match_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData8>, arg6: RawPtr<Pcre2MatchContext8>, arg7: RawPtr<i32>, arg8: u64) -> i32
pub extern "C" fn pcre2_match_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData8>, arg6: RawPtr<Pcre2MatchContext8>) -> i32
pub extern "C" fn pcre2_get_mark_8(arg0: RawPtr<Pcre2MatchData8>) -> RawPtr<u8>
pub extern "C" fn pcre2_get_match_data_size_8(arg0: RawPtr<Pcre2MatchData8>) -> u64
pub extern "C" fn pcre2_get_match_data_heapframes_size_8(arg0: RawPtr<Pcre2MatchData8>) -> u64
pub extern "C" fn pcre2_get_ovector_count_8(arg0: RawPtr<Pcre2MatchData8>) -> u32
pub extern "C" fn pcre2_get_ovector_pointer_8(arg0: RawPtr<Pcre2MatchData8>) -> RawPtr<u64>
pub extern "C" fn pcre2_get_startchar_8(arg0: RawPtr<Pcre2MatchData8>) -> u64
pub extern "C" fn pcre2_next_match_8(arg0: RawPtr<Pcre2MatchData8>, arg1: RawPtr<u64>, arg2: RawPtr<u32>) -> i32
pub extern "C" fn pcre2_substring_copy_byname_8(arg0: RawPtr<Pcre2MatchData8>, arg1: RawPtr<u8>, arg2: RawPtr<u8>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_copy_bynumber_8(arg0: RawPtr<Pcre2MatchData8>, arg1: u32, arg2: RawPtr<u8>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_free_8(arg0: RawPtr<u8>)
pub extern "C" fn pcre2_substring_get_byname_8(arg0: RawPtr<Pcre2MatchData8>, arg1: RawPtr<u8>, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_get_bynumber_8(arg0: RawPtr<Pcre2MatchData8>, arg1: u32, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_byname_8(arg0: RawPtr<Pcre2MatchData8>, arg1: RawPtr<u8>, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_bynumber_8(arg0: RawPtr<Pcre2MatchData8>, arg1: u32, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_nametable_scan_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<RawPtr<u8> >) -> i32
pub extern "C" fn pcre2_substring_number_from_name_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_substring_list_free_8(arg0: RawPtr<RawPtr<u8> >)
pub extern "C" fn pcre2_substring_list_get_8(arg0: RawPtr<Pcre2MatchData8>, arg1: RawPtr<RawPtr<RawPtr<u8> > >, arg2: RawPtr<RawPtr<u64> >) -> i32
pub extern "C" fn pcre2_serialize_encode_8(arg0: RawPtr<RawPtr<Pcre2Code8> >, arg1: i32, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<u64>, arg4: RawPtr<Pcre2GeneralContext8>) -> i32
pub extern "C" fn pcre2_serialize_decode_8(arg0: RawPtr<RawPtr<Pcre2Code8> >, arg1: i32, arg2: RawPtr<u8>, arg3: RawPtr<Pcre2GeneralContext8>) -> i32
pub extern "C" fn pcre2_serialize_get_number_of_codes_8(arg0: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_serialize_free_8(arg0: RawPtr<u8>)
pub extern "C" fn pcre2_substitute_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData8>, arg6: RawPtr<Pcre2MatchContext8>, arg7: RawPtr<u8>, arg8: u64, arg9: RawPtr<u8>, arg10: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_jit_compile_8(arg0: RawPtr<Pcre2Code8>, arg1: u32) -> i32
pub extern "C" fn pcre2_jit_match_8(arg0: RawPtr<Pcre2Code8>, arg1: RawPtr<u8>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData8>, arg6: RawPtr<Pcre2MatchContext8>) -> i32
pub extern "C" fn pcre2_jit_free_unused_memory_8(arg0: RawPtr<Pcre2GeneralContext8>)
pub extern "C" fn pcre2_jit_stack_create_8(arg0: u64, arg1: u64, arg2: RawPtr<Pcre2GeneralContext8>) -> RawPtr<Pcre2JitStack8>
pub extern "C" fn pcre2_jit_stack_assign_8(arg0: RawPtr<Pcre2MatchContext8>, arg1: fn(RawPtr<u8>) -> RawPtr<Pcre2JitStack8>, arg2: RawPtr<u8>)
pub extern "C" fn pcre2_jit_stack_free_8(arg0: RawPtr<Pcre2JitStack8>)
pub extern "C" fn pcre2_get_error_message_8(arg0: i32, arg1: RawPtr<u8>, arg2: u64) -> i32
pub extern "C" fn pcre2_maketables_8(arg0: RawPtr<Pcre2GeneralContext8>) -> RawPtr<u8>
pub extern "C" fn pcre2_maketables_free_8(arg0: RawPtr<Pcre2GeneralContext8>, arg1: RawPtr<u8>)
pub extern "C" fn pcre2_config_16(arg0: u32, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_general_context_copy_16(arg0: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2GeneralContext16>
pub extern "C" fn pcre2_general_context_create_16(arg0: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg1: fn(RawPtr<u8>, RawPtr<u8>), arg2: RawPtr<u8>) -> RawPtr<Pcre2GeneralContext16>
pub extern "C" fn pcre2_general_context_free_16(arg0: RawPtr<Pcre2GeneralContext16>)
pub extern "C" fn pcre2_compile_context_copy_16(arg0: RawPtr<Pcre2CompileContext16>) -> RawPtr<Pcre2CompileContext16>
pub extern "C" fn pcre2_compile_context_create_16(arg0: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2CompileContext16>
pub extern "C" fn pcre2_compile_context_free_16(arg0: RawPtr<Pcre2CompileContext16>)
pub extern "C" fn pcre2_set_bsr_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_character_tables_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_compile_extra_options_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_max_pattern_length_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_pattern_compiled_length_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_varlookbehind_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_newline_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_parens_nest_limit_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_compile_recursion_guard_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: fn(u32, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_optimize_16(arg0: RawPtr<Pcre2CompileContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_convert_context_copy_16(arg0: RawPtr<Pcre2ConvertContext16>) -> RawPtr<Pcre2ConvertContext16>
pub extern "C" fn pcre2_convert_context_create_16(arg0: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2ConvertContext16>
pub extern "C" fn pcre2_convert_context_free_16(arg0: RawPtr<Pcre2ConvertContext16>)
pub extern "C" fn pcre2_set_glob_escape_16(arg0: RawPtr<Pcre2ConvertContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_glob_separator_16(arg0: RawPtr<Pcre2ConvertContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_pattern_convert_16(arg0: RawPtr<u16>, arg1: u64, arg2: u32, arg3: RawPtr<RawPtr<u16> >, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2ConvertContext16>) -> i32
pub extern "C" fn pcre2_converted_pattern_free_16(arg0: RawPtr<u16>)
pub extern "C" fn pcre2_match_context_copy_16(arg0: RawPtr<Pcre2MatchContext16>) -> RawPtr<Pcre2MatchContext16>
pub extern "C" fn pcre2_match_context_create_16(arg0: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2MatchContext16>
pub extern "C" fn pcre2_match_context_free_16(arg0: RawPtr<Pcre2MatchContext16>)
pub extern "C" fn pcre2_set_callout_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: fn(RawPtr<Pcre2CalloutBlock16>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_callout_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: fn(RawPtr<Pcre2SubstituteCalloutBlock16>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_case_callout_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: fn(RawPtr<u16>, u64, RawPtr<u16>, u64, i32, RawPtr<u8>) -> u64, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_depth_limit_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_heap_limit_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_match_limit_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_offset_limit_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_recursion_limit_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_recursion_memory_management_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg2: fn(RawPtr<u8>, RawPtr<u8>), arg3: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_compile_16(arg0: RawPtr<u16>, arg1: u64, arg2: u32, arg3: RawPtr<i32>, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2CompileContext16>) -> RawPtr<Pcre2Code16>
pub extern "C" fn pcre2_code_free_16(arg0: RawPtr<Pcre2Code16>)
pub extern "C" fn pcre2_code_copy_16(arg0: RawPtr<Pcre2Code16>) -> RawPtr<Pcre2Code16>
pub extern "C" fn pcre2_code_copy_with_tables_16(arg0: RawPtr<Pcre2Code16>) -> RawPtr<Pcre2Code16>
pub extern "C" fn pcre2_pattern_info_16(arg0: RawPtr<Pcre2Code16>, arg1: u32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_callout_enumerate_16(arg0: RawPtr<Pcre2Code16>, arg1: fn(RawPtr<Pcre2CalloutEnumerateBlock16>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_match_data_create_16(arg0: u32, arg1: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2MatchData16>
pub extern "C" fn pcre2_match_data_create_from_pattern_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2MatchData16>
pub extern "C" fn pcre2_match_data_free_16(arg0: RawPtr<Pcre2MatchData16>)
pub extern "C" fn pcre2_dfa_match_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData16>, arg6: RawPtr<Pcre2MatchContext16>, arg7: RawPtr<i32>, arg8: u64) -> i32
pub extern "C" fn pcre2_match_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData16>, arg6: RawPtr<Pcre2MatchContext16>) -> i32
pub extern "C" fn pcre2_get_mark_16(arg0: RawPtr<Pcre2MatchData16>) -> RawPtr<u16>
pub extern "C" fn pcre2_get_match_data_size_16(arg0: RawPtr<Pcre2MatchData16>) -> u64
pub extern "C" fn pcre2_get_match_data_heapframes_size_16(arg0: RawPtr<Pcre2MatchData16>) -> u64
pub extern "C" fn pcre2_get_ovector_count_16(arg0: RawPtr<Pcre2MatchData16>) -> u32
pub extern "C" fn pcre2_get_ovector_pointer_16(arg0: RawPtr<Pcre2MatchData16>) -> RawPtr<u64>
pub extern "C" fn pcre2_get_startchar_16(arg0: RawPtr<Pcre2MatchData16>) -> u64
pub extern "C" fn pcre2_next_match_16(arg0: RawPtr<Pcre2MatchData16>, arg1: RawPtr<u64>, arg2: RawPtr<u32>) -> i32
pub extern "C" fn pcre2_substring_copy_byname_16(arg0: RawPtr<Pcre2MatchData16>, arg1: RawPtr<u16>, arg2: RawPtr<u16>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_copy_bynumber_16(arg0: RawPtr<Pcre2MatchData16>, arg1: u32, arg2: RawPtr<u16>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_free_16(arg0: RawPtr<u16>)
pub extern "C" fn pcre2_substring_get_byname_16(arg0: RawPtr<Pcre2MatchData16>, arg1: RawPtr<u16>, arg2: RawPtr<RawPtr<u16> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_get_bynumber_16(arg0: RawPtr<Pcre2MatchData16>, arg1: u32, arg2: RawPtr<RawPtr<u16> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_byname_16(arg0: RawPtr<Pcre2MatchData16>, arg1: RawPtr<u16>, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_bynumber_16(arg0: RawPtr<Pcre2MatchData16>, arg1: u32, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_nametable_scan_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>, arg2: RawPtr<RawPtr<u16> >, arg3: RawPtr<RawPtr<u16> >) -> i32
pub extern "C" fn pcre2_substring_number_from_name_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>) -> i32
pub extern "C" fn pcre2_substring_list_free_16(arg0: RawPtr<RawPtr<u16> >)
pub extern "C" fn pcre2_substring_list_get_16(arg0: RawPtr<Pcre2MatchData16>, arg1: RawPtr<RawPtr<RawPtr<u16> > >, arg2: RawPtr<RawPtr<u64> >) -> i32
pub extern "C" fn pcre2_serialize_encode_16(arg0: RawPtr<RawPtr<Pcre2Code16> >, arg1: i32, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<u64>, arg4: RawPtr<Pcre2GeneralContext16>) -> i32
pub extern "C" fn pcre2_serialize_decode_16(arg0: RawPtr<RawPtr<Pcre2Code16> >, arg1: i32, arg2: RawPtr<u8>, arg3: RawPtr<Pcre2GeneralContext16>) -> i32
pub extern "C" fn pcre2_serialize_get_number_of_codes_16(arg0: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_serialize_free_16(arg0: RawPtr<u8>)
pub extern "C" fn pcre2_substitute_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData16>, arg6: RawPtr<Pcre2MatchContext16>, arg7: RawPtr<u16>, arg8: u64, arg9: RawPtr<u16>, arg10: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_jit_compile_16(arg0: RawPtr<Pcre2Code16>, arg1: u32) -> i32
pub extern "C" fn pcre2_jit_match_16(arg0: RawPtr<Pcre2Code16>, arg1: RawPtr<u16>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData16>, arg6: RawPtr<Pcre2MatchContext16>) -> i32
pub extern "C" fn pcre2_jit_free_unused_memory_16(arg0: RawPtr<Pcre2GeneralContext16>)
pub extern "C" fn pcre2_jit_stack_create_16(arg0: u64, arg1: u64, arg2: RawPtr<Pcre2GeneralContext16>) -> RawPtr<Pcre2JitStack16>
pub extern "C" fn pcre2_jit_stack_assign_16(arg0: RawPtr<Pcre2MatchContext16>, arg1: fn(RawPtr<u8>) -> RawPtr<Pcre2JitStack16>, arg2: RawPtr<u8>)
pub extern "C" fn pcre2_jit_stack_free_16(arg0: RawPtr<Pcre2JitStack16>)
pub extern "C" fn pcre2_get_error_message_16(arg0: i32, arg1: RawPtr<u16>, arg2: u64) -> i32
pub extern "C" fn pcre2_maketables_16(arg0: RawPtr<Pcre2GeneralContext16>) -> RawPtr<u8>
pub extern "C" fn pcre2_maketables_free_16(arg0: RawPtr<Pcre2GeneralContext16>, arg1: RawPtr<u8>)
pub extern "C" fn pcre2_config_32(arg0: u32, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_general_context_copy_32(arg0: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2GeneralContext32>
pub extern "C" fn pcre2_general_context_create_32(arg0: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg1: fn(RawPtr<u8>, RawPtr<u8>), arg2: RawPtr<u8>) -> RawPtr<Pcre2GeneralContext32>
pub extern "C" fn pcre2_general_context_free_32(arg0: RawPtr<Pcre2GeneralContext32>)
pub extern "C" fn pcre2_compile_context_copy_32(arg0: RawPtr<Pcre2CompileContext32>) -> RawPtr<Pcre2CompileContext32>
pub extern "C" fn pcre2_compile_context_create_32(arg0: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2CompileContext32>
pub extern "C" fn pcre2_compile_context_free_32(arg0: RawPtr<Pcre2CompileContext32>)
pub extern "C" fn pcre2_set_bsr_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_character_tables_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_compile_extra_options_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_max_pattern_length_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_pattern_compiled_length_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_max_varlookbehind_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_newline_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_parens_nest_limit_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_compile_recursion_guard_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: fn(u32, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_optimize_32(arg0: RawPtr<Pcre2CompileContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_convert_context_copy_32(arg0: RawPtr<Pcre2ConvertContext32>) -> RawPtr<Pcre2ConvertContext32>
pub extern "C" fn pcre2_convert_context_create_32(arg0: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2ConvertContext32>
pub extern "C" fn pcre2_convert_context_free_32(arg0: RawPtr<Pcre2ConvertContext32>)
pub extern "C" fn pcre2_set_glob_escape_32(arg0: RawPtr<Pcre2ConvertContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_glob_separator_32(arg0: RawPtr<Pcre2ConvertContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_pattern_convert_32(arg0: RawPtr<u32>, arg1: u64, arg2: u32, arg3: RawPtr<RawPtr<u32> >, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2ConvertContext32>) -> i32
pub extern "C" fn pcre2_converted_pattern_free_32(arg0: RawPtr<u32>)
pub extern "C" fn pcre2_match_context_copy_32(arg0: RawPtr<Pcre2MatchContext32>) -> RawPtr<Pcre2MatchContext32>
pub extern "C" fn pcre2_match_context_create_32(arg0: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2MatchContext32>
pub extern "C" fn pcre2_match_context_free_32(arg0: RawPtr<Pcre2MatchContext32>)
pub extern "C" fn pcre2_set_callout_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: fn(RawPtr<Pcre2CalloutBlock32>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_callout_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: fn(RawPtr<Pcre2SubstituteCalloutBlock32>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_substitute_case_callout_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: fn(RawPtr<u32>, u64, RawPtr<u32>, u64, i32, RawPtr<u8>) -> u64, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_set_depth_limit_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_heap_limit_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_match_limit_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_offset_limit_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: u64) -> i32
pub extern "C" fn pcre2_set_recursion_limit_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: u32) -> i32
pub extern "C" fn pcre2_set_recursion_memory_management_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: fn(u64, RawPtr<u8>) -> RawPtr<u8>, arg2: fn(RawPtr<u8>, RawPtr<u8>), arg3: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_compile_32(arg0: RawPtr<u32>, arg1: u64, arg2: u32, arg3: RawPtr<i32>, arg4: RawPtr<u64>, arg5: RawPtr<Pcre2CompileContext32>) -> RawPtr<Pcre2Code32>
pub extern "C" fn pcre2_code_free_32(arg0: RawPtr<Pcre2Code32>)
pub extern "C" fn pcre2_code_copy_32(arg0: RawPtr<Pcre2Code32>) -> RawPtr<Pcre2Code32>
pub extern "C" fn pcre2_code_copy_with_tables_32(arg0: RawPtr<Pcre2Code32>) -> RawPtr<Pcre2Code32>
pub extern "C" fn pcre2_pattern_info_32(arg0: RawPtr<Pcre2Code32>, arg1: u32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_callout_enumerate_32(arg0: RawPtr<Pcre2Code32>, arg1: fn(RawPtr<Pcre2CalloutEnumerateBlock32>, RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_match_data_create_32(arg0: u32, arg1: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2MatchData32>
pub extern "C" fn pcre2_match_data_create_from_pattern_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2MatchData32>
pub extern "C" fn pcre2_match_data_free_32(arg0: RawPtr<Pcre2MatchData32>)
pub extern "C" fn pcre2_dfa_match_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData32>, arg6: RawPtr<Pcre2MatchContext32>, arg7: RawPtr<i32>, arg8: u64) -> i32
pub extern "C" fn pcre2_match_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData32>, arg6: RawPtr<Pcre2MatchContext32>) -> i32
pub extern "C" fn pcre2_get_mark_32(arg0: RawPtr<Pcre2MatchData32>) -> RawPtr<u32>
pub extern "C" fn pcre2_get_match_data_size_32(arg0: RawPtr<Pcre2MatchData32>) -> u64
pub extern "C" fn pcre2_get_match_data_heapframes_size_32(arg0: RawPtr<Pcre2MatchData32>) -> u64
pub extern "C" fn pcre2_get_ovector_count_32(arg0: RawPtr<Pcre2MatchData32>) -> u32
pub extern "C" fn pcre2_get_ovector_pointer_32(arg0: RawPtr<Pcre2MatchData32>) -> RawPtr<u64>
pub extern "C" fn pcre2_get_startchar_32(arg0: RawPtr<Pcre2MatchData32>) -> u64
pub extern "C" fn pcre2_next_match_32(arg0: RawPtr<Pcre2MatchData32>, arg1: RawPtr<u64>, arg2: RawPtr<u32>) -> i32
pub extern "C" fn pcre2_substring_copy_byname_32(arg0: RawPtr<Pcre2MatchData32>, arg1: RawPtr<u32>, arg2: RawPtr<u32>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_copy_bynumber_32(arg0: RawPtr<Pcre2MatchData32>, arg1: u32, arg2: RawPtr<u32>, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_free_32(arg0: RawPtr<u32>)
pub extern "C" fn pcre2_substring_get_byname_32(arg0: RawPtr<Pcre2MatchData32>, arg1: RawPtr<u32>, arg2: RawPtr<RawPtr<u32> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_get_bynumber_32(arg0: RawPtr<Pcre2MatchData32>, arg1: u32, arg2: RawPtr<RawPtr<u32> >, arg3: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_byname_32(arg0: RawPtr<Pcre2MatchData32>, arg1: RawPtr<u32>, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_length_bynumber_32(arg0: RawPtr<Pcre2MatchData32>, arg1: u32, arg2: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_substring_nametable_scan_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>, arg2: RawPtr<RawPtr<u32> >, arg3: RawPtr<RawPtr<u32> >) -> i32
pub extern "C" fn pcre2_substring_number_from_name_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>) -> i32
pub extern "C" fn pcre2_substring_list_free_32(arg0: RawPtr<RawPtr<u32> >)
pub extern "C" fn pcre2_substring_list_get_32(arg0: RawPtr<Pcre2MatchData32>, arg1: RawPtr<RawPtr<RawPtr<u32> > >, arg2: RawPtr<RawPtr<u64> >) -> i32
pub extern "C" fn pcre2_serialize_encode_32(arg0: RawPtr<RawPtr<Pcre2Code32> >, arg1: i32, arg2: RawPtr<RawPtr<u8> >, arg3: RawPtr<u64>, arg4: RawPtr<Pcre2GeneralContext32>) -> i32
pub extern "C" fn pcre2_serialize_decode_32(arg0: RawPtr<RawPtr<Pcre2Code32> >, arg1: i32, arg2: RawPtr<u8>, arg3: RawPtr<Pcre2GeneralContext32>) -> i32
pub extern "C" fn pcre2_serialize_get_number_of_codes_32(arg0: RawPtr<u8>) -> i32
pub extern "C" fn pcre2_serialize_free_32(arg0: RawPtr<u8>)
pub extern "C" fn pcre2_substitute_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData32>, arg6: RawPtr<Pcre2MatchContext32>, arg7: RawPtr<u32>, arg8: u64, arg9: RawPtr<u32>, arg10: RawPtr<u64>) -> i32
pub extern "C" fn pcre2_jit_compile_32(arg0: RawPtr<Pcre2Code32>, arg1: u32) -> i32
pub extern "C" fn pcre2_jit_match_32(arg0: RawPtr<Pcre2Code32>, arg1: RawPtr<u32>, arg2: u64, arg3: u64, arg4: u32, arg5: RawPtr<Pcre2MatchData32>, arg6: RawPtr<Pcre2MatchContext32>) -> i32
pub extern "C" fn pcre2_jit_free_unused_memory_32(arg0: RawPtr<Pcre2GeneralContext32>)
pub extern "C" fn pcre2_jit_stack_create_32(arg0: u64, arg1: u64, arg2: RawPtr<Pcre2GeneralContext32>) -> RawPtr<Pcre2JitStack32>
pub extern "C" fn pcre2_jit_stack_assign_32(arg0: RawPtr<Pcre2MatchContext32>, arg1: fn(RawPtr<u8>) -> RawPtr<Pcre2JitStack32>, arg2: RawPtr<u8>)
pub extern "C" fn pcre2_jit_stack_free_32(arg0: RawPtr<Pcre2JitStack32>)
pub extern "C" fn pcre2_get_error_message_32(arg0: i32, arg1: RawPtr<u32>, arg2: u64) -> i32
pub extern "C" fn pcre2_maketables_32(arg0: RawPtr<Pcre2GeneralContext32>) -> RawPtr<u8>
pub extern "C" fn pcre2_maketables_free_32(arg0: RawPtr<Pcre2GeneralContext32>, arg1: RawPtr<u8>)
